version: '3.4'

services:
  cas_proxy:
    image: cas-proxy
    environment:
      SERVER_NAME: localhost
      CAS_HOST: cas.example.edu
      CAS_USERS: 'example'
      PROXY_TARGET: http://backend:8080
      CAS_PROXY_HOST: http://localhost:8080
    ports:
    - target: 80
      published: 8080
      protocol: tcp
      mode: ingress
  backend:
    image: brndnmtthws/nginx-echo-headers:latest
